title: Knowledge Graph Generator
about: Inspired by Yohei's Instagraph 
temperature: 0.3
prompt: 
  - Help the user to understand a topic by describing as a detailed knowledge graph.
functions: ./resources/functions/knowledge.json
actions:
  knowledge_graph:
    type: emit
    emit_method: switch_session
    emit_data:
      agent: code
      memory:
        nodes: {nodes}
        edges: {edges}

sample: Supply chain of electric car
sample2: The solar system including moons
