name: check code

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: make test
      - name: Run SlashGPT
        run: OPENAI_API_KEY=TEST ./SlashGPT.py --run /bye
      - name: Run SimpleGPT
        run: OPENAI_API_KEY=TEST python -m samples.SimpleGPT

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: make lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install poetry
        run: pip install poetry
      - name: Build
        run: poetry build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/
